config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'

  get 'user' => 'users#show'
  get 'user/edit' => 'users#edit'
  patch 'user' => 'users#show'

  resources :users
  resources :restaurants
  resources :google_maps

  root :to => 'restaurants#index'
  resources :user_sessions
  

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/google_map.rb
class GoogleMap < ActiveRecord::Base
	has_one :user
	belongs_to :restaurant

	
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :users


end

app/models/user.rb
class User < ActiveRecord::Base
	
	authenticates_with_sorcery!

	validates :password, length: { minimum: 7 }
	validates :password, confirmation: true
	validates :password_confirmation, presence: true

	validates :email, uniqueness: true

	# has_many :customers
	has_many :restaurants

	# Early attempt at basic admin function
		# def is_max?
	 #    	if @user.email == 'maxd924@gmail.com'
	 #      		redirect_to :users
	 #    	end
    	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  private
	def not_authenticated
  		redirect_to login_path, alert: "Please login first"
	end
end

app/controllers/google_maps_controller.rb
class GoogleMapsController < ApplicationController

end 

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_filter :require_login, only: [:index]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
	def index
		@restaurants = Restaurant.all
	end

	#Show data for one restaurant
	def show
		@restaurant = Restaurant.find(params[:id])
	end

	# Displays form for creating a new restaurant
	def new
		@restaurant = Restaurant.new
	end

	# Processes data from the new restaurant form and creates a restaurant
	def create
	    @restaurant = Restaurant.new(restaurant_params)

	    #respond_to do |format|
	      if @restaurant.save
			redirect_to restaurants_url, notice: 'Restaurant was successfully created.' 
	        #format.json { render :show, status: :created, location: @restaurant }
	      else
	        render :new 
	        #format.json { render json: @restaurant.errors, status: :unprocessable_entity }
	      end
	    #end
	end

	# Displays form for editing an existing restaurant
	def edit

	end

	# Processes data from the edit restaurant from and updates the restaurant
	def update
	    #respond_to do |format|
	      if @restaurant.update(restaurant_params)
	        redirect_to @restaurant, notice: 'restaurant was successfully updated.'
	        #format.json { render :show, status: :ok, location: @restaurant }
	      else
	        render :edit 
	        #format.json { render json: @restaurant.errors, status: :unprocessable_entity }
	      end
	    # end
	end

	# Deletes the restaurant
	def destroy
		# Restaurant.find(params[:id]).destroy		
	    @restaurant.destroy
	    respond_to do |format|
	      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
	    end
	end

 private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :spicy, :cost, :vegetarian)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_filter :require_login, except: [:destroy]
  def new
  	@user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      # Last minute admin addition which gave me the ability 
      # to delete obnoxious restaurant additions made by my 
      # classmates during my presentation
      $veg = @user.email
      redirect_back_or_to('/user', notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
  	logout
    $veg = ""
    redirect_to(:restaurants, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create ]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  # Shows all of the restaurants
  def index
     redirect_to :restaurants
  end

  # Utilizes the google maps API to show where the restaurant is on the map
  def show
  end

  # Makes a new use
  def new
    @user = User.new
  end

  # Edits users
  def edit
    @users = User.all
  end

  # Creates/saves new user to the database
  def create
    @user = User.new(user_params)

    #respond_to do |format|
      if @user.save
        auto_login(@user)
        redirect_to(@user, notice: 'User was successfully created')
      else
        render :new 
      end
    #end
  end

  # Update user
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Deletes user
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :spicy, :vegetarian)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SomeLikeItHot</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
<!--       <link rel="shortcut icon" href="/app/assets/images/taco.png"> -->

      <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  <body>

  <div id="nav" class="rest_text"><h1>
    <% if current_user %>
      <%= link_to "Edit Profile", user_edit_path %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </h1></div>
  <div>
    <h1><p id="notice"><%#= flash[:notice] %></p></h1>
    <h1><p id="alert"><%#= flash[:alert] %></p></h1>
  </div>
  <%= yield %>
  
  </body>
</html>

app/views/restaurants/_form.html.erb
 <%= form_for(@restaurant, :html => {:class => "formDiv"}) do |f| %>
 
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    
    Pricing
      <div class="field">
      <%= f.select :cost do %>
        <%= [['Cheap', 'cheap'], ['Average', 'average'], ['Expensive', 'expensive']].each do |v| %>
          <%= content_tag(:option, v.first, value: v.last) %>
        <% end %>
      <% end %>
    </div>

    Vegetarian friendly?
      <div class="field">
      <%= f.select :vegetarian do %>
        <%= [['Yes', 'Yes'], ['No', 'No']].each do |v| %>
          <%= content_tag(:option, v.first, value: v.last) %>
        <% end %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

  </div>
<% end %>

app/views/restaurants/delete.html.erb
<!-- Only admin can access this page to delete restaurants  -->
 <p id="notice"><%= notice %></p>

<h1 class="rest_text"><strong>All Restaurants</strong></h1>

<div class="main_list">

    <% @restaurants.each do |restaurant| %>
        <div class="indiv_restaurant">
            <strong>Name: </strong></br>
            <p><%= restaurant.name %><br>
           <strong>Address:</strong><br>
            <%= restaurant.address %><br>
            <strong>Cost:</strong>
            <%= restaurant.cost.titleize %><br>
            <strong>Vegetarian Friendly?</strong>
            <%= restaurant.vegetarian.to_s %><br>
            <%= link_to 'Show', restaurant %></p>
            <%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
        </div>
    <% end %>

</div>
    


<p class="rest_text"><%= link_to 'Add a new restaurant', new_restaurant_path %></p>

app/views/restaurants/edit.html.erb
 <h1>Edit Restaurant</h1>

<%= render 'form' %>
<h1>
<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>
</h1>

app/views/restaurants/index.html.erb
 <p id="notice"><h1><%= notice %></h1></p>

<div>
    <h1 class="rest_text"><strong>All Restaurants</strong></h1>
</div>

<div class="main_list">
    <% @restaurants.each do |restaurant| %>
        <div class="indiv_restaurant">
            <strong>Name: </strong></br>
            <p><%= restaurant.name %><br>
           <strong>Address:</strong><br>
            <%= restaurant.address %><br>
            <strong>Cost:</strong>
            <%= restaurant.cost.titleize %><br>
            <strong>Vegetarian Friendly?</strong>
            <%= restaurant.vegetarian.to_s %><br>
            <%= link_to 'Show', restaurant %>
            <!-- Last minute admin addition which gave me the ability to delete obnoxious additions made by my classmates  --> 
            <% if $veg == 'maxd924@yahoo.com' %>          
                <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </p>
        </div>
    <% end %>

</div>
    


<h1><p class="rest_text"><%= link_to 'Add a new restaurant', new_restaurant_path %></p></h1>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<!DOCTYPE HTML>
<html>

<head>
    <title>Where is it?</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map-canvas {
        height: 100%;
        width: 100%;
        margin: 0 auto;
        padding: 0px
      }
      #map_box  {
        height: 100%;
        width: 100%;
        position: absolute;
      }
    </style>

    <%= javascript_include_tag "application" %>

    
  </head>
  <body>
  	<p id="notice"><%= notice %></p>
    <h6 id="address" style="color:white"><%= @restaurant.address %></h6><br>
    <h1 class="rest_text"><strong><%= @restaurant.name %></strong></h1>


    <div id="map_box">
      <div id="map-canvas"></div>
    </div>

        <script>
            $(document).ready(function() {
              loadScript();
            });
            

	    	  

	    </script>
  </body>
</html>

<%= link_to 'Back', restaurants_path %></h1>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Taco Meccas', :restaurants %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "formDiv"}) do |f| %>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
   <%= f.label :password %><br /><span id="password_info">
   *Must be 7 characters long</span><br />
   <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<% if $veg == 'maxd924@gmail.com' %>
	<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<%= render 'form' %>

<% end %>

<h1><%= link_to 'Show', user_path %> |
<%= link_to 'Taco Places', :restaurants %></h1>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1><%= link_to 'New User', new_user_path %><br>
<%= link_to 'Edit Restaurants', :restaurants %></h1>

app/views/users/new.html.erb
<h1>New User</h1>
	<%= render 'form' %>
	
<h1><%= link_to 'Taco Joints', :restaurants %></h1>

app/views/users/show.html.erb
<h1><p id="notice"><%= notice %></p></h1>

<h3><p>
  <strong>Email:</strong>
  <%= @user.email %>
</p></h3>
<!-- Last minute admin addition which gave me the ability to delete obnoxious additions made by my classmates  -->
<% if $veg == 'maxd924@yahoo.com' %>
	<h1>
	<%= link_to 'Edit', edit_user_path(@user) %> 
	</h1>
<% end %>
<h1><%= link_to 'Taco Places', :restaurants %></h1>